name: Clojure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test and Build
      run: lein do clean, compile :all, test, uberjar, cljsbuild once min
